name: DOA
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  # 如果没有 NVIDIA GPU/CUDA，可删除下一行并使用 CPU 版 PyTorch。
  - pytorch-cuda=11.8
  - pytorch=2.5.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - pip
  - pip:
      - tensorboardX
      - tqdm
      - pandas
      - scikit-learn
      - matplotlib
      - prettytable

